# Generated by Django 3.2.4 on 2021-06-29 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('Deleted User'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citymodel',
            name='land',
            field=models.ForeignKey(null=True, on_delete=models.SET('Unknown'), to='backend.landmodel'),
        ),
        migrations.AddField(
            model_name='landmodel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('Deleted User'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npcmodel',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=models.SET('Deleted User'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='npcmodel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=models.SET('Unknown'), to='backend.citymodel'),
        ),
    ]
