# Generated by Django 3.2.4 on 2021-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210629_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npcmodel',
            old_name='date',
            new_name='date_added',
        ),
        migrations.AddField(
            model_name='citymodel',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
